import type { Application } from "express";
import { registerAgentic } from "./agentic.js";
import { registerAgents } from "./agents.js";
import { registerAmbientAsyncEndToEnd } from "./ambientAsyncEndToEnd.js";
import { registerAmbientAsyncFacts } from "./ambientAsyncFacts.js";
import { registerAmbientRtStreams } from "./ambientRtStreams.js";
import { registerClientVariants } from "./clientVariants.js";
import { registerCodes } from "./codes.js";
import { registerDocuments } from "./documents.js";
import { registerFacts } from "./facts.js";
import { registerGuidedDocuments } from "./guidedDocuments.js";
import { registerGuidedDocumentsCrud } from "./guidedDocumentsCrud.js";
import { registerGuidedSections } from "./guidedSections.js";
import { registerGuidedTemplates } from "./guidedTemplates.js";
import { registerInteractions } from "./interactions.js";
import { registerLanguages } from "./languages.js";
import { registerRecordings } from "./recordings.js";
import { registerStream } from "./stream.js";
import { registerStreamWithConfig } from "./streamWithConfig.js";
import { registerTemplates } from "./templates.js";
import { registerToken } from "./token.js";
import { registerTranscribe } from "./transcribe.js";
import { registerTranscribeWithConfig } from "./transcribeWithConfig.js";
import { registerTranscripts } from "./transcripts.js";

export function registerRoutes(app: Application): void {
  registerToken(app);
  registerClientVariants(app);
  registerInteractions(app);
  registerRecordings(app);
  registerTranscripts(app);
  registerFacts(app);
  registerCodes(app);
  registerLanguages(app);
  registerTemplates(app);
  registerAgents(app);
  registerAgentic(app);
  registerDocuments(app);
  registerGuidedSections(app);
  registerGuidedTemplates(app);
  registerGuidedDocuments(app);
  registerGuidedDocumentsCrud(app);
  registerStream(app);
  registerStreamWithConfig(app);
  registerTranscribe(app);
  registerTranscribeWithConfig(app);
  registerAmbientAsyncEndToEnd(app);
  registerAmbientAsyncFacts(app);
  registerAmbientRtStreams(app);
}
