import { guidedSectionPicker } from "./guidedSections";
import { LANGUAGE_CODES, LANGUAGE_LABELS } from "./languages";
import type { BodyField, EndpointDef, ParamPicker, ResponseField } from "./types";

// ---- Pickers --------------------------------------------------------------

// Templates live under /documents/templates — the new "guided" template system.
// Path params take templateID + versionID UUIDs; templateID is pickable via the
// LIST endpoint, versionID needs templateID resolved first.
export const guidedTemplatePicker: ParamPicker = {
  fromEndpoint: "guidedTemplates.list",
  valueField: ["id"],
  labelFields: ["name", "id"],
  createEndpoint: "guidedTemplates.create",
  createLabel: "Create template",
};

export const guidedTemplateVersionPicker: ParamPicker = {
  fromEndpoint: "guidedTemplates.listVersions",
  valueField: ["id"],
  labelFields: ["versionNumber", "id"],
  parentParams: [
    {
      to: { in: "path", name: "templateID" },
      from: { in: "path", name: "templateID" },
      label: "template",
    },
  ],
};

// ---- Shared schema parts -------------------------------------------------

// A template's `generation` block — its own prompt + an ordered list of section refs.
// Reused as-is for full create and (partial) for version create when inheriting.
const templateGenerationField: BodyField = {
  name: "generation",
  kind: "object",
  required: true,
  fields: [
    {
      name: "instructions",
      kind: "object",
      required: true,
      fields: [
        {
          name: "prompt",
          kind: "string",
          required: true,
          multiline: true,
          rows: 4,
          description: "Template-level prompt that applies to every section.",
        },
      ],
    },
    {
      name: "sections",
      kind: "array",
      description: "Ordered list of section references that make up this template.",
      item: {
        name: "sectionRef",
        kind: "object",
        fields: [
          {
            name: "sectionId",
            kind: "uuid",
            required: true,
            picker: guidedSectionPicker,
            description: "Section to include. Pick from your section library.",
          },
          {
            name: "orderIndex",
            kind: "number",
            description: "Position in the template (0-indexed). Lower comes first.",
          },
        ],
      },
    },
  ],
};

const labelsField: BodyField = {
  name: "labels",
  kind: "array",
  description: "Tag-style labels for filtering on LIST /templates.",
  item: {
    name: "label",
    kind: "object",
    fields: [
      { name: "key", kind: "string", required: true },
      { name: "value", kind: "string", required: true },
    ],
  },
};

const policyItemField: BodyField = {
  name: "policy",
  kind: "object",
  fields: [
    {
      name: "kind",
      kind: "enum",
      required: true,
      enum: ["project", "customers"],
      description:
        "`project` restricts to the owning project; `customers` grants access to listed tenants.",
    },
    {
      name: "customerIds",
      kind: "array",
      description: "Required when kind=customers. Tenant ids that should have access.",
      item: { name: "id", kind: "string" },
      showWhen: { field: "kind", equals: "customers" },
    },
  ],
};

// ---- Response shapes -----------------------------------------------------

const templateResponseFields: ResponseField[] = [
  { name: "id", kind: "uuid", description: "Template id." },
  { name: "name", kind: "string" },
  { name: "description", kind: "string" },
  { name: "languages", kind: "array", item: { name: "lang", kind: "string" } },
  { name: "regions", kind: "array", item: { name: "region", kind: "string" } },
  { name: "specialties", kind: "array", item: { name: "specialty", kind: "string" } },
  {
    name: "labels",
    kind: "array",
    item: {
      name: "label",
      kind: "object",
      fields: [
        { name: "key", kind: "string" },
        { name: "value", kind: "string" },
      ],
    },
  },
  {
    name: "inheritedFromId",
    kind: "uuid",
    description: "Parent template id if this one inherits.",
  },
  { name: "autoGenerated", kind: "boolean" },
  { name: "source", kind: "string", description: "user | corti" },
  { name: "createdAt", kind: "datetime" },
  { name: "updatedAt", kind: "datetime" },
  {
    name: "publishedVersion",
    kind: "object",
    description: "Currently published version with inheritance fully resolved.",
    fields: [
      { name: "id", kind: "uuid" },
      { name: "versionNumber", kind: "number" },
      { name: "generation", kind: "json", description: "Fully resolved template generation tree." },
    ],
  },
];

const templateVersionResponseFields: ResponseField[] = [
  { name: "id", kind: "uuid", description: "Version id." },
  { name: "versionNumber", kind: "number", description: "0-indexed, auto-incremented." },
  {
    name: "generation",
    kind: "object",
    description: "Authored (un-resolved) generation — section refs only.",
    fields: [
      {
        name: "instructions",
        kind: "object",
        fields: [{ name: "prompt", kind: "string" }],
      },
      {
        name: "sections",
        kind: "array",
        item: {
          name: "ref",
          kind: "object",
          fields: [
            { name: "sectionId", kind: "uuid" },
            { name: "orderIndex", kind: "number" },
          ],
        },
      },
    ],
  },
  { name: "publishedAt", kind: "datetime" },
  { name: "deletedAt", kind: "datetime" },
];

const policyResponseFields: ResponseField[] = [
  { name: "id", kind: "uuid" },
  { name: "kind", kind: "string", description: "project | customers" },
  { name: "templateId", kind: "uuid" },
  { name: "createdBy", kind: "uuid" },
  { name: "createdAt", kind: "datetime" },
  { name: "updatedAt", kind: "datetime" },
  { name: "customerIds", kind: "array", item: { name: "id", kind: "string" } },
];

// ---- Endpoints ------------------------------------------------------------

export const guidedTemplates: EndpointDef[] = [
  // LIST -----------------------------------------------------------------
  {
    id: "guidedTemplates.list",
    group: "Guided Templates",
    method: "GET",
    path: "/documents/templates/",
    label: "List templates",
    description:
      "List guided templates and metadata. Fetch a specific templateID to see the expanded section references.",
    queryParams: [
      { name: "lang", in: "query", description: "BCP 47 tag (e.g. en, fr, en-GB). Repeatable." },
      {
        name: "region",
        in: "query",
        description: "ISO 3166-1 alpha-3 code (e.g. BEL). Repeatable.",
      },
      { name: "specialty", in: "query", description: "Clinical specialty. Repeatable." },
      { name: "label", in: "query", description: "key:value label filter. Repeatable." },
      { name: "published", in: "query", kind: "boolean" },
      { name: "source", in: "query", description: "user | corti" },
    ],
    body: { kind: "none" },
    responseSchema: [
      {
        name: "items",
        kind: "array",
        item: { name: "template", kind: "object", fields: templateResponseFields },
      },
    ],
  },

  // GET / UPDATE / DELETE on a template ----------------------------------
  {
    id: "guidedTemplates.get",
    group: "Guided Templates",
    method: "GET",
    path: "/documents/templates/{templateID}",
    label: "Get template",
    description:
      "Fetch a single template, including its published version with inheritance fully resolved.",
    pathParams: [{ name: "templateID", in: "path", required: true, picker: guidedTemplatePicker }],
    body: { kind: "none" },
    responseSchema: templateResponseFields,
  },
  {
    id: "guidedTemplates.update",
    group: "Guided Templates",
    method: "PATCH",
    path: "/documents/templates/{templateID}",
    label: "Update template metadata",
    description:
      "Update template metadata (name, description, languages, regions, specialties, labels). Only fields you fill in are sent.",
    pathParams: [{ name: "templateID", in: "path", required: true, picker: guidedTemplatePicker }],
    body: {
      kind: "json",
      schema: [
        { name: "name", kind: "string" },
        { name: "description", kind: "string", multiline: true, rows: 3 },
        {
          name: "languages",
          kind: "array",
          item: { name: "lang", kind: "enum", enum: LANGUAGE_CODES, enumLabels: LANGUAGE_LABELS },
        },
        {
          name: "regions",
          kind: "array",
          item: { name: "region", kind: "string", example: "BEL" },
        },
        { name: "specialties", kind: "array", item: { name: "specialty", kind: "string" } },
        labelsField,
      ],
    },
    responseSchema: templateResponseFields,
  },
  {
    id: "guidedTemplates.delete",
    group: "Guided Templates",
    method: "DELETE",
    path: "/documents/templates/{templateID}",
    label: "Delete template",
    description: "Soft-delete a template and all its versions.",
    pathParams: [{ name: "templateID", in: "path", required: true, picker: guidedTemplatePicker }],
    body: { kind: "none" },
  },

  // CREATE template -----------------------------------------------------
  {
    id: "guidedTemplates.create",
    group: "Guided Templates",
    method: "POST",
    path: "/documents/templates/",
    label: "Create template",
    description:
      "Create a new template with an initial version. When `publish` is true (default), the response includes the published version with inheritance resolved at both template and section levels.",
    body: {
      kind: "json",
      schema: [
        {
          name: "name",
          kind: "string",
          required: true,
          description: "Template display name. Not passed to the LLM.",
        },
        { name: "description", kind: "string", multiline: true, rows: 2 },
        templateGenerationField,
        {
          name: "languages",
          kind: "array",
          item: {
            name: "lang",
            kind: "enum",
            enum: LANGUAGE_CODES,
            enumLabels: LANGUAGE_LABELS,
            example: "en",
          },
        },
        {
          name: "regions",
          kind: "array",
          item: { name: "region", kind: "string", example: "BEL" },
        },
        { name: "specialties", kind: "array", item: { name: "specialty", kind: "string" } },
        labelsField,
        {
          name: "publish",
          kind: "boolean",
          description:
            "Defaults to true. Set false to keep the new template out of LIST /templates.",
        },
        {
          name: "policies",
          kind: "array",
          description: "Initial access policies (defaults to project-scoped).",
          item: policyItemField,
        },
        {
          name: "inheritFromId",
          kind: "uuid",
          picker: guidedTemplatePicker,
          description:
            "Optional. When set, inherits instructions + sections from this template's published version, and `generation` is treated as partial overrides.",
        },
      ],
    },
    responseSchema: templateResponseFields,
  },

  // VERSIONS -----------------------------------------------------------
  {
    id: "guidedTemplates.listVersions",
    group: "Guided Templates",
    method: "GET",
    path: "/documents/templates/{templateID}/versions/",
    label: "List template versions",
    description: "All versions of a template, oldest first. Use the version id with Get / Publish.",
    pathParams: [{ name: "templateID", in: "path", required: true, picker: guidedTemplatePicker }],
    body: { kind: "none" },
    responseSchema: [
      {
        name: "items",
        kind: "array",
        item: { name: "version", kind: "object", fields: templateVersionResponseFields },
      },
    ],
  },
  {
    id: "guidedTemplates.getVersion",
    group: "Guided Templates",
    method: "GET",
    path: "/documents/templates/{templateID}/versions/{versionID}",
    label: "Get template version",
    description: "Fetch a specific version (raw authored values, no inheritance resolution).",
    pathParams: [
      { name: "templateID", in: "path", required: true, picker: guidedTemplatePicker },
      { name: "versionID", in: "path", required: true, picker: guidedTemplateVersionPicker },
    ],
    body: { kind: "none" },
    responseSchema: templateVersionResponseFields,
  },
  {
    id: "guidedTemplates.createVersion",
    group: "Guided Templates",
    method: "POST",
    path: "/documents/templates/{templateID}/versions/",
    label: "Create template version",
    description:
      "Create a new draft version of a template. When the template inherits, fields you omit are inherited from the parent's published version.",
    pathParams: [{ name: "templateID", in: "path", required: true, picker: guidedTemplatePicker }],
    body: {
      kind: "json",
      schema: [templateGenerationField],
    },
    responseSchema: templateVersionResponseFields,
  },
  {
    id: "guidedTemplates.deleteVersion",
    group: "Guided Templates",
    method: "DELETE",
    path: "/documents/templates/{templateID}/versions/{versionID}",
    label: "Delete template version",
    description: "Soft-delete a template version.",
    pathParams: [
      { name: "templateID", in: "path", required: true, picker: guidedTemplatePicker },
      { name: "versionID", in: "path", required: true, picker: guidedTemplateVersionPicker },
    ],
    body: { kind: "none" },
  },
  {
    id: "guidedTemplates.publishVersion",
    group: "Guided Templates",
    method: "POST",
    path: "/documents/templates/{templateID}/versions/{versionID}/publish",
    label: "Publish template version",
    description:
      "Mark a version as the published one. Document generation uses this version going forward.",
    pathParams: [
      { name: "templateID", in: "path", required: true, picker: guidedTemplatePicker },
      { name: "versionID", in: "path", required: true, picker: guidedTemplateVersionPicker },
    ],
    body: { kind: "none" },
    responseSchema: templateVersionResponseFields,
  },

  // POLICIES -----------------------------------------------------------
  {
    id: "guidedTemplates.listPolicies",
    group: "Guided Templates",
    method: "GET",
    path: "/documents/templates/{templateID}/policies/",
    label: "List template policies",
    description: "All access policies attached to a template.",
    pathParams: [{ name: "templateID", in: "path", required: true, picker: guidedTemplatePicker }],
    body: { kind: "none" },
    responseSchema: [
      {
        name: "items",
        kind: "array",
        item: { name: "policy", kind: "object", fields: policyResponseFields },
      },
    ],
  },
  {
    id: "guidedTemplates.createPolicies",
    group: "Guided Templates",
    method: "POST",
    path: "/documents/templates/{templateID}/policies/",
    label: "Create template policies",
    description: "Attach access policies to a template.",
    pathParams: [{ name: "templateID", in: "path", required: true, picker: guidedTemplatePicker }],
    body: {
      kind: "json",
      schema: [
        {
          name: "items",
          kind: "array",
          required: true,
          description:
            "Policies to attach. Use kind=customers + customerIds to grant cross-tenant access.",
          item: policyItemField,
        },
      ],
    },
    responseSchema: [
      {
        name: "items",
        kind: "array",
        item: { name: "policy", kind: "object", fields: policyResponseFields },
      },
    ],
  },
];
