type SeedPatient = {
  fullName: string;
  dob: string;
  sex: string;
  phone: string;
  email: string;
  address: string;
  nhsNumber: string;
  allergies: string;
  chronicConditions: string;
};

type SeedAppointment = {
  patientIndex: number;
  startsAt: string;
  clinician: string;
  reason: string;
  status: "upcoming" | "checked-in";
};

type SeedVisit = {
  patientIndex: number;
  visitDate: string;
  clinician: string;
  reason: string;
  subjective: string;
  objective?: string;
  bloodPressure?: string;
  heartRate?: number;
  temperatureC?: number;
  assessment: string;
  plan: string;
  outcomeType: "none" | "prescription" | "referral";
  outcomeDetails?: string;
};

const patients: SeedPatient[] = [
  {
    fullName: "Eleanor Shaw",
    dob: "1981-04-12",
    sex: "Female",
    phone: "07700 900101",
    email: "eleanor.shaw@example.test",
    address: "14 Kingfisher Row, Brighton",
    nhsNumber: "943 476 1820",
    allergies: "Penicillin",
    chronicConditions: "Asthma",
  },
  {
    fullName: "James Patel",
    dob: "1974-09-03",
    sex: "Male",
    phone: "07700 900102",
    email: "james.patel@example.test",
    address: "2 Willow Close, Hove",
    nhsNumber: "943 476 1821",
    allergies: "None recorded",
    chronicConditions: "Hypertension",
  },
  {
    fullName: "Maya O'Connell",
    dob: "1992-01-26",
    sex: "Female",
    phone: "07700 900103",
    email: "maya.oconnell@example.test",
    address: "7 Station Terrace, Lewes",
    nhsNumber: "943 476 1822",
    allergies: "Latex",
    chronicConditions: "Migraine",
  },
  {
    fullName: "Noah Bennett",
    dob: "1988-07-18",
    sex: "Male",
    phone: "07700 900104",
    email: "noah.bennett@example.test",
    address: "33 Orchard Lane, Brighton",
    nhsNumber: "943 476 1823",
    allergies: "Ibuprofen",
    chronicConditions: "None recorded",
  },
  {
    fullName: "Grace Li",
    dob: "1969-11-08",
    sex: "Female",
    phone: "07700 900105",
    email: "grace.li@example.test",
    address: "5 Victoria Mews, Hove",
    nhsNumber: "943 476 1824",
    allergies: "None recorded",
    chronicConditions: "Type 2 diabetes",
  },
  {
    fullName: "Arthur Doyle",
    dob: "1958-06-21",
    sex: "Male",
    phone: "07700 900106",
    email: "arthur.doyle@example.test",
    address: "18 Selsey Road, Peacehaven",
    nhsNumber: "943 476 1825",
    allergies: "Shellfish",
    chronicConditions: "COPD",
  },
  {
    fullName: "Freya Ahmed",
    dob: "2001-03-09",
    sex: "Female",
    phone: "07700 900107",
    email: "freya.ahmed@example.test",
    address: "24 Marine Parade, Brighton",
    nhsNumber: "943 476 1826",
    allergies: "None recorded",
    chronicConditions: "Eczema",
  },
  {
    fullName: "Leo Carmichael",
    dob: "2010-10-15",
    sex: "Male",
    phone: "07700 900108",
    email: "parent.leo@example.test",
    address: "9 Portland Street, Hove",
    nhsNumber: "943 476 1827",
    allergies: "Peanuts",
    chronicConditions: "Seasonal allergies",
  },
  {
    fullName: "Sofia Hart",
    dob: "1995-12-02",
    sex: "Female",
    phone: "07700 900109",
    email: "sofia.hart@example.test",
    address: "61 Clifton Hill, Brighton",
    nhsNumber: "943 476 1828",
    allergies: "None recorded",
    chronicConditions: "Anxiety",
  },
  {
    fullName: "Daniel Green",
    dob: "1983-05-30",
    sex: "Male",
    phone: "07700 900110",
    email: "daniel.green@example.test",
    address: "3 Ivy Court, Hove",
    nhsNumber: "943 476 1829",
    allergies: "None recorded",
    chronicConditions: "Gout",
  },
  {
    fullName: "Amelia Rhodes",
    dob: "1979-08-19",
    sex: "Female",
    phone: "07700 900111",
    email: "amelia.rhodes@example.test",
    address: "87 Ditchling Road, Brighton",
    nhsNumber: "943 476 1830",
    allergies: "Sulfa drugs",
    chronicConditions: "Hypothyroidism",
  },
  {
    fullName: "Henry Foster",
    dob: "1990-02-14",
    sex: "Male",
    phone: "07700 900112",
    email: "henry.foster@example.test",
    address: "12 Norfolk Square, Brighton",
    nhsNumber: "943 476 1831",
    allergies: "None recorded",
    chronicConditions: "None recorded",
  },
  {
    fullName: "Lily Brooks",
    dob: "2005-09-29",
    sex: "Female",
    phone: "07700 900113",
    email: "lily.brooks@example.test",
    address: "4 Elm Rise, Shoreham",
    nhsNumber: "943 476 1832",
    allergies: "None recorded",
    chronicConditions: "Acne",
  },
  {
    fullName: "Thomas Kerr",
    dob: "1964-04-04",
    sex: "Male",
    phone: "07700 900114",
    email: "thomas.kerr@example.test",
    address: "27 Seaview Avenue, Worthing",
    nhsNumber: "943 476 1833",
    allergies: "Codeine",
    chronicConditions: "Atrial fibrillation",
  },
  {
    fullName: "Ruby Sinclair",
    dob: "1987-01-11",
    sex: "Female",
    phone: "07700 900115",
    email: "ruby.sinclair@example.test",
    address: "16 Albert Road, Brighton",
    nhsNumber: "943 476 1834",
    allergies: "None recorded",
    chronicConditions: "PCOS",
  },
  {
    fullName: "Oscar Wood",
    dob: "1971-07-27",
    sex: "Male",
    phone: "07700 900116",
    email: "oscar.wood@example.test",
    address: "8 Chapel Street, Lewes",
    nhsNumber: "943 476 1835",
    allergies: "None recorded",
    chronicConditions: "High cholesterol",
  },
  {
    fullName: "Hannah Rees",
    dob: "1998-06-05",
    sex: "Female",
    phone: "07700 900117",
    email: "hannah.rees@example.test",
    address: "22 Trafalgar Lane, Brighton",
    nhsNumber: "943 476 1836",
    allergies: "None recorded",
    chronicConditions: "None recorded",
  },
  {
    fullName: "Jacob Flynn",
    dob: "2016-11-23",
    sex: "Male",
    phone: "07700 900118",
    email: "parent.jacob@example.test",
    address: "10 Pelham Street, Hove",
    nhsNumber: "943 476 1837",
    allergies: "Egg",
    chronicConditions: "Mild eczema",
  },
  {
    fullName: "Ava McKenzie",
    dob: "1949-02-28",
    sex: "Female",
    phone: "07700 900119",
    email: "ava.mckenzie@example.test",
    address: "45 Regency Court, Brighton",
    nhsNumber: "943 476 1838",
    allergies: "None recorded",
    chronicConditions: "Osteoarthritis",
  },
  {
    fullName: "Samuel Price",
    dob: "1985-10-07",
    sex: "Male",
    phone: "07700 900120",
    email: "samuel.price@example.test",
    address: "6 Church Lane, Hove",
    nhsNumber: "943 476 1839",
    allergies: "None recorded",
    chronicConditions: "GERD",
  },
];

const appointments: SeedAppointment[] = [
  {
    patientIndex: 0,
    startsAt: "2026-04-19T09:00:00",
    clinician: "Dr. Mason",
    reason: "Asthma medication review",
    status: "upcoming",
  },
  {
    patientIndex: 1,
    startsAt: "2026-04-19T09:30:00",
    clinician: "Dr. Mason",
    reason: "Blood pressure follow-up",
    status: "upcoming",
  },
  {
    patientIndex: 2,
    startsAt: "2026-04-19T10:15:00",
    clinician: "Dr. Reed",
    reason: "Headache assessment",
    status: "checked-in",
  },
  {
    patientIndex: 4,
    startsAt: "2026-04-19T11:00:00",
    clinician: "Dr. Reed",
    reason: "Diabetes review",
    status: "upcoming",
  },
  {
    patientIndex: 7,
    startsAt: "2026-04-19T11:30:00",
    clinician: "Dr. Mason",
    reason: "School health note",
    status: "upcoming",
  },
  {
    patientIndex: 9,
    startsAt: "2026-04-19T13:30:00",
    clinician: "Dr. Mason",
    reason: "Joint pain",
    status: "upcoming",
  },
  {
    patientIndex: 12,
    startsAt: "2026-04-19T14:00:00",
    clinician: "Dr. Reed",
    reason: "Skin review",
    status: "upcoming",
  },
  {
    patientIndex: 15,
    startsAt: "2026-04-19T15:15:00",
    clinician: "Dr. Mason",
    reason: "Cholesterol review",
    status: "upcoming",
  },
];

const visits: SeedVisit[] = [
  {
    patientIndex: 0,
    visitDate: "2026-03-10T09:00:00",
    clinician: "Dr. Mason",
    reason: "Cough and wheeze",
    subjective: "Night symptoms twice a week, inhaler technique reviewed.",
    bloodPressure: "122/78",
    heartRate: 76,
    temperatureC: 36.8,
    assessment: "Mild asthma flare, no signs of infection.",
    plan: "Continue preventer, increase reliever use for 48 hours.",
    outcomeType: "prescription",
    outcomeDetails: "Salbutamol inhaler",
  },
  {
    patientIndex: 1,
    visitDate: "2026-02-21T10:30:00",
    clinician: "Dr. Reed",
    reason: "Hypertension review",
    subjective: "Home readings improving, no headaches or chest pain.",
    bloodPressure: "134/82",
    heartRate: 68,
    temperatureC: 36.6,
    assessment: "Controlled hypertension.",
    plan: "Maintain current medication and repeat home monitoring.",
    outcomeType: "none",
  },
  {
    patientIndex: 2,
    visitDate: "2026-01-18T14:15:00",
    clinician: "Dr. Mason",
    reason: "Migraine review",
    subjective: "Increased frequency after poor sleep.",
    bloodPressure: "118/72",
    heartRate: 72,
    temperatureC: 36.7,
    assessment: "Migraine without red flags.",
    plan: "Headache diary and trigger management.",
    outcomeType: "prescription",
    outcomeDetails: "Sumatriptan 50 mg",
  },
  {
    patientIndex: 4,
    visitDate: "2026-03-28T11:45:00",
    clinician: "Dr. Reed",
    reason: "Diabetes check",
    subjective: "Diet stable, occasional afternoon fatigue.",
    bloodPressure: "128/74",
    heartRate: 70,
    temperatureC: 36.6,
    assessment: "Type 2 diabetes under reasonable control.",
    plan: "Repeat HbA1c next month.",
    outcomeType: "none",
  },
  {
    patientIndex: 5,
    visitDate: "2026-02-04T09:20:00",
    clinician: "Dr. Mason",
    reason: "Breathlessness",
    subjective: "Walking tolerance reduced over the winter.",
    bloodPressure: "136/80",
    heartRate: 82,
    temperatureC: 36.9,
    assessment: "COPD symptoms increased, no acute infection.",
    plan: "Pulmonary rehab referral.",
    outcomeType: "referral",
    outcomeDetails: "Community respiratory team",
  },
  {
    patientIndex: 6,
    visitDate: "2026-03-16T16:00:00",
    clinician: "Dr. Reed",
    reason: "Rash flare",
    subjective: "Dry, itchy patches on flexures.",
    bloodPressure: "110/68",
    heartRate: 74,
    temperatureC: 36.5,
    assessment: "Eczema flare.",
    plan: "Regular emollient and short course steroid cream.",
    outcomeType: "prescription",
    outcomeDetails: "Hydrocortisone 1% cream",
  },
  {
    patientIndex: 8,
    visitDate: "2026-04-02T13:10:00",
    clinician: "Dr. Mason",
    reason: "Low mood",
    subjective: "Stress at work, sleep disrupted, no immediate risk concerns.",
    bloodPressure: "116/70",
    heartRate: 78,
    temperatureC: 36.7,
    assessment: "Anxiety symptoms with sleep disturbance.",
    plan: "Self-referral talking therapy information given.",
    outcomeType: "referral",
    outcomeDetails: "Primary care mental health service",
  },
  {
    patientIndex: 10,
    visitDate: "2026-02-27T12:30:00",
    clinician: "Dr. Reed",
    reason: "Tiredness",
    subjective: "Symptoms stable on current thyroid medication.",
    bloodPressure: "124/76",
    heartRate: 71,
    temperatureC: 36.6,
    assessment: "Likely routine thyroid review.",
    plan: "Repeat thyroid blood tests.",
    outcomeType: "none",
  },
  {
    patientIndex: 13,
    visitDate: "2026-03-07T15:40:00",
    clinician: "Dr. Mason",
    reason: "Palpitations follow-up",
    subjective: "No syncope, symptoms brief and intermittent.",
    bloodPressure: "130/78",
    heartRate: 80,
    temperatureC: 36.5,
    assessment: "Known AF, rate acceptable.",
    plan: "Continue current management, safety-net for worsening symptoms.",
    outcomeType: "none",
  },
  {
    patientIndex: 18,
    visitDate: "2026-01-29T10:00:00",
    clinician: "Dr. Reed",
    reason: "Knee pain",
    subjective: "Pain worse after walking, morning stiffness under 30 minutes.",
    bloodPressure: "138/84",
    heartRate: 73,
    temperatureC: 36.4,
    assessment: "Likely osteoarthritis flare.",
    plan: "Exercise sheet and topical analgesia.",
    outcomeType: "prescription",
    outcomeDetails: "Topical diclofenac gel",
  },
];

export const seedData = {
  patients,
  appointments,
  visits,
};
